version: "3.8"

services:
  epi_generator:
    build: .
    container_name: epi_generator_container
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "main.py"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "8000:8000"
